# Generated by Django 4.2.27 on 2025-12-17 06:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'Category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClosureCode',
            fields=[
                ('id', models.UUIDField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ClosureCode',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='tickets.category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='accounts.department')),
            ],
            options={
                'verbose_name_plural': 'SubCategories',
                'db_table': 'SubCategory',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('status', models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Waiting', 'Waiting'), ('On Hold', 'On Hold'), ('Closed', 'Closed')], db_index=True, default='New', max_length=50)),
                ('is_closed', models.BooleanField(db_index=True, default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to='accounts.user')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.category')),
                ('closure_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.closurecode')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to='accounts.user')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='accounts.department')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.subcategory')),
            ],
            options={
                'db_table': 'Ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.UUIDField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('note', models.TextField()),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_changes', to='accounts.user')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='tickets.ticket')),
            ],
            options={
                'verbose_name_plural': 'Ticket Histories',
                'db_table': 'TicketHistory',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['ticket', '-changed_at'], name='IX_History_Ticket'), models.Index(fields=['changed_by', 'changed_at'], name='IX_History_ChangedBy')],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.UUIDField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='tickets.ticket')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to='accounts.user')),
            ],
            options={
                'db_table': 'TicketAttachment',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['ticket', 'uploaded_at'], name='IX_Attachment_Ticket')],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['-created_at', 'id'], name='IX_Ticket_Pagination'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to', 'is_closed', 'status'], name='IX_Ticket_AssignedTo'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['department', 'status', 'is_closed'], name='IX_Ticket_Department'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_by', '-created_at'], name='IX_Ticket_CreatedBy'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to', 'is_closed', 'closed_at'], name='IX_Ticket_Analytics'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'created_at'], name='IX_Ticket_Status'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(check=models.Q(('is_closed', False), models.Q(('is_closed', True), ('closure_code__isnull', False), ('closed_at__isnull', False)), _connector='OR'), name='CK_Ticket_ClosureData'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(check=models.Q(('priority__isnull', True), models.Q(('priority__gte', 1), ('priority__lte', 4)), _connector='OR'), name='CK_Ticket_Priority'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category', 'department'], name='IX_SubCat_CatDept'),
        ),
    ]
