# Generated by Django 4.2.27 on 2025-12-18 05:31

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, help_text='Event type: ticket_create, status_change, etc.', max_length=50)),
                ('entity_type', models.CharField(db_index=True, help_text='Entity type: Ticket, EmailIngest, User, etc.', max_length=50)),
                ('entity_id', models.UUIDField(db_index=True, help_text='UUID of the affected entity')),
                ('actor_id', models.UUIDField(blank=True, db_index=True, help_text='User who performed the action (null for system events)', null=True)),
                ('actor_email', models.CharField(blank=True, help_text='Actor email at time of action', max_length=255, null=True)),
                ('actor_roles', models.CharField(blank=True, help_text='Comma-separated roles at time of action', max_length=255, null=True)),
                ('request_id', models.CharField(db_index=True, help_text='Correlation ID from request logging', max_length=36)),
                ('payload', models.JSONField(default=dict, help_text='Event-specific data')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Client user agent', max_length=500, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the event occurred')),
            ],
            options={
                'db_table': 'AuditLog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='IX_Audit_Entity'), models.Index(fields=['actor_id', '-created_at'], name='IX_Audit_Actor'), models.Index(fields=['event_type', '-created_at'], name='IX_Audit_EventType'), models.Index(fields=['request_id'], name='IX_Audit_RequestId')],
            },
        ),
    ]
