# Generated by Django 4.2.27 on 2025-12-19 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0002_alter_category_id_alter_closurecode_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailIngest',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_email', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField()),
                ('received_at', models.DateTimeField()),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('is_discarded', models.BooleanField(default=False)),
                ('discarded_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_emails', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_emails', to='tickets.ticket')),
            ],
            options={
                'db_table': 'EmailIngest',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email_intake.emailingest')),
            ],
            options={
                'db_table': 'EmailAttachment',
                'ordering': ['file_name'],
            },
        ),
        migrations.AddIndex(
            model_name='emailingest',
            index=models.Index(fields=['is_processed', 'is_discarded'], name='IX_Email_Status'),
        ),
        migrations.AddIndex(
            model_name='emailingest',
            index=models.Index(fields=['received_at'], name='IX_Email_Received'),
        ),
    ]
